name: Publish Charts to /docs
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Package and Publish charts
      uses: J12934/helm-gh-pages-action@master
      with:
        access-token: "${{ secrets.CR_TOKEN }}"
